# Build
custom_build(
    # Name of image name
    ref = 'edge-service',

    # command to build container image
    command = './gradlew bootBuildImage --imageName $EXPECTED_REF',

    # files to watch that trigger a new build
    deps = ['build.gradle', 'src']
)

# Deploy
k8s_yaml(['k8s/deployment.yml', 'k8s/service.yml'])

# Manage
k8s_resource('edge-service', port_forwards=['9000'])